### ISSUE TITLE
user story 1 

### ISSUE THREAD

**Issue by jonas8900** [jonas8900/Capstone-project#1]
## Create info-card on the dashboard 

as a friend 
i want to see the next planned activity 
so i don't forget about it

## Description

![Bildschirmfoto 2023-08-11 um 16 32 38](https://github.com/jonas8900/Capstone-project/assets/123127839/5ebf6bcd-ad8d-49f2-b2a7-89015f964502)

## Acceptance criteria

- the page has a headline with the title “Friends”
- there is a card with the information of the next planned activity
- the card has a headline with the Text “nächste Aktivität” 
- the card shows the following details: time, date, activity and the location
- the card is placed in the center of the page

## Tasks

- [ ] create a branch with the name dashboard-activity-card
- [ ] create a component with the name Dashboard
- [ ] create a component with the name DashboardCard 
- [ ] create a section inside the DashboardCard
- [ ] create a h1 with the name “Friends” in the center.
- [ ] import styled components and create a 
- [ ] 1. styled.h2 with color: var(secondary) and border-bottom
styled.ul with display: grid
- [ ] 2. create the styled.h2, styled.ul and 4 li elements
- [ ] the li elements are structured like this: date, activity, time, location 
- [ ] create a root with the colors in the styled.js (global-styles):  primary: #FF4D4D, 
       secondary: #FF3B17, third: #FFC44D,  fourth: #4D4DFF, fifth: #4D17C9

## Size
small
