### ISSUE TITLE
User story 6 (Create a dynamic route to plan a activity)

### ISSUE THREAD

**Issue by jonas8900** [jonas8900/Capstone-project#10]
## Value proposition Create a dynamic route to plan a activity

as a user 
i want to plan the activity with a choise of multiple dates
to adapt the activity to the other schedules

## Description

![image](https://github.com/jonas8900/Capstone-project/assets/123127839/c3fe52e6-d122-4cd4-b9f5-0df7bc4e3dba)

## Acceptance criteria

- onclick to the “plan” button on “Aktivitäten”-page a new page appear 
- the new page shows a Headline named “Welches Datum passt” and a subheadline named “plane deine nächste Aktivität” and a card with some details.
- Inside the details-card is the topic “Veranstaltung”. Below the Topic there are 4 possible dates to get the date when the most users have time.
- you need to select the “Datum” but the other 3 dates are not necessary, but is better to fill them!
- the “Bestätigen” button is not useable for now

## Tasks

- [ ] create a branch with the name “add-dynamic-route-for-activityplans”
- [ ] create a file with the name [activityPlan]
- [ ] we need the useRouter function to check if we got the same ID like the ID we clicked (Grillabend id: 1 / router.query > id1)
- [ ] when the id matches the name “Grillabend” should be accepted in the [activityPlan] page. 
- [ ] create 2 headlines like in the description.
- [ ] the [activityPlan] page needs  a form with 4 date-pickers, but the user should not be able to confirm with 2 same dates.
- [ ] each date is an inputs with the type: date, wrapped by a label.

## Size
medium

**Comment by jonas8900** [comment]
Thank you for your time !! :) i'll Keeper that in my mind for the next us ! Thanks
