### ISSUE TITLE
User story 7 (fetch the dates from the activities)

### ISSUE THREAD

**Issue by jonas8900** [jonas8900/Capstone-project#13]
## Value proposition

as a user 
i want to vote for a date the starts activity 
to be able to choose the dates when I have time

![image](https://github.com/jonas8900/Capstone-project/assets/123127839/f65521b3-096e-46b2-8ebd-95cc53b333da)

## Acceptance criteria

- after we plan a activity with some dates, we can see a new window on the dashboard
- the window show us the activity and some dates we can vote for
- you can choose multiple dates,  just one, or non of them (Kein Datum passt).
- after submit the choosen dates, the statistik about the vote appears.
- you can now see, how many people choose a date
- you can also see how many people doesnt choose dates at all in the (keine Abstimmung von) part.
- if you see, everyone vote for a date, you can click on this date and close the vote.
- you have now a new planned activity ! 

## Tasks

- [ ] create a new branch with the name “fetch-data-for-vote”
- [ ] take the data from the dateobject and drill the prop to the dashboard, so we can reach the object we submitted with dates on the dashboard.
- [ ] create a component with the name “ Votecard”
- [ ] create a Headline and a form with labels and checkboxes.
- [ ] put the dataObject we have into the labels so we can see the dates as the text. 
- [ ] when we click at the “bestätigen” button, we should have a object with the dates we choose and after clickling, a hardcodet statistic appears, the statistic has no functionality for now

## Size
Medium

**Comment by F-Kirchhoff** [comment]
I like that you add the functionality later on and focus in this user story on the input part. 
I guess you can simplify the display / entering of the data that you have less states your event display has to go through. Maybe you should focus in this user story mainly on 
- adding dates for the event (in the creation form / edit form of the event)
- displaying the dates in the detail page

Everything else can be put in a future user story.

For the acceptance criteria, it sounds a bit like a guide for a user how to use the new feature. You are missing out a lot of visual elements that you would need for the user story but didn't mention. Try to think about every single component / element that you need to add for this user story and list them as well. (Another point why you should shrink this user story as mentioned above). 
The same is true for the tasks, please try to add more detail here what components you need to create / props you need and so on. With the reduced content of your user story this will be much easier. 
Good luck!

**Comment by jonas8900** [comment]
Thank you very much for your time ! I've failed a bit with the description. The first two pages are completed and are working so i can focus to fetch the data and create a "Abstimmung der nächsten Veranstaltung" on the Dashboard. 

so i'll shrink this story and focused only on the "page 3" like in your comment. i'll think about how to make the data structure more simplify and will correct my acceptance criteria. Thank you ! :)

**Comment by jonas8900** [comment]
the object should contain the old data and some new keys like this: date1IsChecked: true; date2IsChecked: true, < don't coded this, because this was a bad idea, i added a new attribute with the name 'dateXIsTrue: "value"`
