### ISSUE TITLE
User story 8 (Close the vote and have a new event)

### ISSUE THREAD

**Issue by jonas8900** [jonas8900/Capstone-project#14]
## Value proposition

as a user 
i want to choose a final date and see the event on the page “Veranstaltungen”
to have an overview of the planned activitys.

## Description

![image](https://github.com/jonas8900/Capstone-project/assets/123127839/a8595810-a965-493a-a5e6-95a6914d1d29)

## Acceptance criteria

- after you commited your votes, a new window will be displayed with all the important stats for the voting.
- there is the same headline and the same activity as before 
- below the activity, there is a list of the dates with a number of people who voted for this date and the part with “keine Abstimmung von”, but there is no function yet but it'll be important for later user stories!
- on the bottom of the window you can select a date.
- with the button below the date-selector you can confirm the date you want 
- after you clicked on the "Abstimmung abschließen" button, the window will disappear
- the window is on top of the page. 

## Tasks

- [x] create a new branch with the name “add-final-date-selector”
- [x] inside the component VoteCard we need to handle the submit with the handleSubmitChecked function 
- [x] first hardcode the dates and the count for the people and the "keine Abstimmung von" part. 
- [x] create a submitbutton and onsubmit change the state to the date you choose in the select with the name of the activity.
- [x] create a form with a <select> of all the possible dates and the option to choose no date and store the information about the event (name) in the object and store this in the dates state 
- [x] create a new page with the name “Veranstaltungen” 
- [x] grab the information from the state with the final date and the name of the activity
- [x] map over the state with the objects that has the final dates and the activity names and display them in the “Veranstaltungen” page. 

## Size
Medium

**Comment by alper92** [comment]
Looks good to me! Much success!
