### ISSUE TITLE
User story 9 (code refactoring)

### ISSUE THREAD

**Issue by jonas8900** [jonas8900/Capstone-project#19]
## Value proposition code refactoring

no feature, only improvement!

## Description

![image](https://github.com/jonas8900/Capstone-project/assets/123127839/60d83660-d9e4-4646-8d5f-bbb7edbb3fe7)

## Acceptance criteria

- improve the readability of my code

## Tasks

- [ ] maybe source out the votecard in a component
- [ ] fix the issue that you can submit data without click on a date 
- [ ] fix confusing names like 3 times “StyledSection”.
- [ ] delete not used variables.
- [ ] look at the html semantic (like a map function which renders an UL every time)
- [ ] fix the bugs: "uncontrolled input", "styled components classname not match", "each child need a unique key prop"

## Size
small

**Comment by dm-nosov** [comment]
Looks good!
