### ISSUE TITLE
User story 2 (Create an activity-list)

### ISSUE THREAD

**Issue by jonas8900** [jonas8900/Capstone-project#2]
## Value proposition Create an activity-list 

As a user
I want to see a list of all possible activities
To be able to get inspired and choose the next group activity

## Description

![image](https://github.com/jonas8900/Capstone-project/assets/123127839/011d74de-ba08-4c6c-be0f-27a0b479f140)
## Acceptance criteria

-  the activity-list should contain a headline with the text “Aktivitäten”
-  each list-item should have the same size and the text with the activity.
- the scrollbehaviour is vertically 
- each list-item has the same distance to the top, right and left

## Tasks

- [ ] create a branch with the name activity-list
- [ ] create a folder with the name “dummyList” 
- [ ] and an js file with the name: activityList.js
- [ ] create a variable with an array of objects with the name: activityList
- [ ] every object need a name and an id
- [ ] create 4 objects with the name from the description
- [ ] create a component with the name Activitylist
- [ ] create a h1 with the name “Friends” in the center.
- [ ] create a section inside the Activitylist component
- [ ] create a h2 with the name “Aktivitäten” 
- [ ] import styled components and place the h2 in the left corner on the top
- [ ] create an ul, import the dummyList and map over the activitylist
- [ ] style each list item like the description

## Size
medium

**Comment by ninaassmann** [comment]
LGTM
