### ISSUE TITLE
User story 10 (create delete and add function)

### ISSUE THREAD

**Issue by jonas8900** [jonas8900/Capstone-project#21]
## Value proposition

As a user, 
i want to add or delete an event, 
to be able to add a fix event or delete a wrong one
 
## Description

![image](https://github.com/jonas8900/Capstone-project/assets/123127839/dc1717f2-7e41-4d1f-a498-968765f08502)

## Acceptance criteria

- [ ] on the "veranstaltungen" page there is a red + symbol on the top of the page with the name "Add activity"
- [ ] by clicking the red + icon, a new formular will appear.
- [ ] in the formular you can write down a event, a location and a date
- [ ] When you click on the "Event hinzufügen" button a new Event will appear with the written data
- [ ] on each event there is a black x on top in the right corner
- [ ] by clicking the x, an window appears with the question "Bist du dir sicher, dass du das Event löschen möchtest?"
- [ ] by clicking "Ja" on the window, the clicked Event will be delete

## Tasks

- [ ] create a branch with the name "add-event-form-and-delete-events" 
- [ ] add a button on each card with an X as text in the veranstaltungen page
- [ ] add a handledeletefunction to the button.
- [ ] in the function, filter the events without the clicked one and add an alert before set. 
- [ ] Add a button which routes to a new page (addevent)
- [ ] add a form on the addevent page like in the description. 
- [ ] onsubmit add the formdataobject to the dates
- [ ] be careful to have the same structure like the other objects in the dates state for the future!
- [ ] build a back button with a route to the veranstaltungen page if you want to cancel the adding.

## Size
M
