### ISSUE TITLE
User story 11 (add favorite button and style the headline)

### ISSUE THREAD

**Issue by jonas8900** [jonas8900/Capstone-project#23]
## Value proposition

as a user, 
i want to like a activity
to be able to mark the activities i like 

## Description

![image](https://github.com/jonas8900/Capstone-project/assets/123127839/ced418be-1f71-4451-97c6-1a354abbaa7c)

## Acceptance criteria

- on the Aktivitäten page, each activity has a empty heart on the right top of each activity-card
- after clicking on the heart, the color turns into red.
- we can see a counter on the right of the heart
- the headline on the top has a logo with the name “Friends”

## Tasks

- [ ] create a new branch with the name “add-favorite-button” 
- [ ] go to the activity.js and add a unfilled heart icon
- [ ] beside the heart create a p tag with a hardcoded number
- [ ] when we click at the heart it should be stored in localstorage to save what activity we like
- [ ] the number beside the heart should start with a random nuber but should increase with 1 after clicking it and decrease after clicking and unfill the heart. 
- [ ] to reach this add a state which counts the number of objects we have in the array
- [ ] by clicking the heart a object with a fake user-id(a random number which i declair as my user-id) should be added and with another click set the state to all objects without the object with my user-id
- [ ] add the logo to the _app.js in the h1
- [ ] style the border from the h1 with a linear gradiend.

## Size
S

**Comment by milodevhh** [comment]
Hey Jonas, looks good to me, have fun with that US, keep on going your App is already a great one!
