### ISSUE TITLE
User story 12 (add eventplanerlist)

### ISSUE THREAD

**Issue by jonas8900** [jonas8900/Capstone-project#24]
## Value proposition

as a user
i want to see who takes which products to which event
to be able to coordinate the shopping

## Description

![image](https://github.com/jonas8900/Capstone-project/assets/123127839/d9a4a60a-d782-4f43-b50d-cc3a46dadbd3)

## Acceptance criteria

- in the menu are three cards with the names “Aktivitäten, Events and Feierplaner. 
- each item has a individual icon 
- by clicking on the card with the name “feierplaner” a new page appear
- on the page is a heading with the name of the card “Feierplaner” with a subheading “Anstehende Aktivität:”
- below this Subheadline is a card, filled with information about the activity (Aktivität, Ort, Datum)
- below the information are something like a shoppinglist with two headlines “name” and “nimmt mit”
- at the bottom of the page is an inputfield with an submit-button 
- when you write down an input, the name “Jonas” appears in the card with the written input under the “nimmt mit:” headline.

## Tasks

- [ ] create a branch with the name "add-feierplaner" 
- [ ] create a new page with the name “Feierplaner.js”
- [ ] create a new link with an icon in the menu.js with the name “Feierplaner”
- [ ] create a new component with the name “FeierplanerCard.js
- [ ] import the FeierplanerCard.js in the page and drill the prop “dates, setDates” down to the component
- [ ] inside the FeierplanerCard style the card like in the description and hardcode the headlines + Details
- [ ] import the “Form” component and create a handleSubmitProducts function which set the single date in dates with a new attribute like this: productsForEvent: [{username: “Jonas”, product: “Bauette”}, {username: “Jonas”, product: “Ketchup”}], the username should be hardcoded at first.
- [ ] map over the dates to show every event, delete the hardcoded activity, location and date and set it to the date.activityname, date.ort, date.finalDate
- [ ] to not display every object which has no property with the name “finalDate”, do conditional rendering below the map method.

**Comment by F-Kirchhoff** [comment]
Hey Jonas,
this is almost perfect, you only should use english when you name your components (partyPlanner instead of Feierplaner). And one question: Wouldn't it be better if you could see this list on every of your planned events and not just one? Maybe you want to consider to add this list to the details page of the events instead of creating this new one.

**Comment by jonas8900** [comment]
This is a very very good idea to add a dynamic route as detail page for each event ! Thank you very much ! I'll change the german names to english names ! :)

**Comment by izabelladobielewska** [comment]
Looks ready :)
