### ISSUE TITLE
User story 13 (connect MongoDB)

### ISSUE THREAD

**Issue by jonas8900** [jonas8900/Capstone-project#26]
## Value proposition

As an user
I want to see the votes of all the other users
to be able to choose the right date when the most have time

## Description

![image](https://github.com/jonas8900/Capstone-project/assets/123127839/7c7589eb-3505-470c-a603-0f02c334a5ea)

## Acceptance criteria

- when you choose the final date in the vote process on your dashboard, you see how many people voted for each date. You can see this right beside the dates in the middle of the voting window. 
- on the activities page you can see how many people liked the activity. The number is right beside the heart on each card. 

## Tasks

- [ ] create a branch with the name "add-mongoDB-connection"
- [ ] create a new database in mongoDB Atlas called capstone-project
- [ ] take a look in the documentation about the connection to a cloud database and set this up to my project
- [ ] first, dont touch the components, only set the database up with the api route
- [ ] ###important!! check your env.local to not share the database URI with github.
- [ ] create a new folder with the name "db" in the project and a new file with the name "connect.js and set it up like in the documentation
- [ ] create a new folder and a new schema for the likes on the activities and for the final votes.
- [ ] after completing the models and the connection, replace the set-functions with the data-base commands 
- [ ] test if the data-base works by checking the mongoDB database and look in the app if for example the count on the activity works.

## Size
L

**Comment by KilianBau** [comment]
really detailed US I like that! Good luck with it when you'll code it 👍
