### ISSUE TITLE
User story 14 (add User-login)

### ISSUE THREAD

**Issue by jonas8900** [jonas8900/Capstone-project#27]
## Value proposition

as a user
i want to vote for events or like an activity with my initials,
to be able to for example see which one of my friends doesn't vote at all

## Description

![image](https://github.com/jonas8900/Capstone-project/assets/123127839/46690a04-a34e-4cc9-b5a4-aa9ef47bff76)

## Acceptance criteria

- [ ] you see a sign-in button on the Dashboard, the other pages (aktivitäten & events) are empty at first.
- [ ] by clicking the button a new page appear with a "sign in with github" window in the middle of the screen.
- [ ] by clicking this, the github-page appears and you are able to authorize your account with github. 
- [ ] by accept the github authorization you come back to the dashboard
- [ ] the dashboard has all the data from your group.

## Tasks

- [ ] create a branch with the name "add-user-login"
- [ ] install next-auth with npm
- [ ] go step-by-step through the next-auth setup (add Api-route....)
- [ ] in the route add a provider from Github
- [ ] add the session provider to the _app.js
- [ ] set the auth up in Github (Register a new OAuth application).
- [ ] be very careful with the secrets you get from Github!!!!!!!
- [ ] work with the useSession, signIn and signOut from next-auth to get the session information we need ! 
- [ ] create a callback (jwt) to get the same token.id as the user.id and return the token
- [ ] example for the logout: create a <p> tag with "angemeldet als: {session.user.email}!

## Size
L

**Comment by chris-kuehn** [comment]
Hi Jonas!

I like your UserStory! The description picture reflects your acceptance criteria and the acceptance criteria itself is clear and easy to follow.

The task list is detailed und well structured.

Only i do not really understand value proposition and i do not see the connection to the rest of your userStory. May i miss a point here? ;)

My suggestion is to write something like:

As a user,
i want to log in to the app 
in order to interact in my friends group.

**Comment by jonas8900** [comment]
Thank you Chris ! :) Your review is perfect! I like your advice with the Value proposition so much, that i don't have a better one !Thank you :)

**Comment by chris-kuehn** [comment]
Yeahhhhhh!
