### ISSUE TITLE
User story 3 (Create an inputfield in the activitylist)

### ISSUE THREAD

**Issue by jonas8900** [jonas8900/Capstone-project#3]
## Value proposition Create an inputfield in the activitylist

As a user
I want to add a new activity to the list
To save my ideas

## Description

![Bildschirmfoto 2023-08-14 um 11 14 45](https://github.com/jonas8900/Capstone-project/assets/123127839/78c4e84e-8398-4104-94c2-b6569f23d9c7)

## Acceptance criteria

- At the bottom of the page is an inputfield with a button on the right.
- The inputfield needs a textinput.
- The inputfield stays in the position while scrolling.
- To confirm and add the new activity to the list you need to press the button beside the inputfield.

## Tasks

- [ ] create a new branch with the name "add-form-component"
- [ ] create a new Component with the Name “Form.js”
- [ ] create a new form with a label, an inputfield and a button 
- [ ] to reuse the form component (dumb) set props as attributes in the inputfield and lift the props up.
- [ ] lift the attribute “onSubmit” in the form as prop up
- [ ] import the form in the Activitylist component 
- [ ] add a handleSubmit function in the Activitylist component to get the data we enter
- [ ] the handleSubmit function contains a variable with the name inputData it contains
 an object with the infos of the card and a unique id.
- [ ] connect the form onSubmit prop with the handleSubmit function.
- [ ] reset the inputfield after submit

## Size
medium
