### ISSUE TITLE
User story 15 (styling)

### ISSUE THREAD

**Issue by jonas8900** [jonas8900/Capstone-project#31]
## Value proposition

as a user, 
i want to be catched from the design,
to be able to use the app intuitive.

## Description

add animations, change the margin from each card to have a better responsive design, refactor my code a bit.

## Acceptance criteria

- i can see on my mobilephone an attractive design 
- the useability is userfriendly and intuitive

## Tasks

- [ ] make a branch with the name "change-styling" 
- [ ] go through the pages and change some issues like the back arrow when you want to plan an activity
- [ ] while i go through the pages i'll change some code issues.

## Size
Small
