### ISSUE TITLE
User story 16 (protect my api route)

### ISSUE THREAD

**Issue by jonas8900** [jonas8900/Capstone-project#32]
## Value proposition

as a user,
i want to be save with sharing my data
to have the privilege to not worry about my safety.

## Description
![image](https://github.com/jonas8900/Capstone-project/assets/123127839/ced71389-08ed-4cb8-8d62-82811c2fdd4d)

- use middleware in next.js to not getting attacked by thomas again.

## Acceptance criteria

- [ ] there is no change on each page except you are not logged-in or you try to reach data from a group you not in.

## Tasks

- [ ] create a new branch with the name "add-protection"
- [ ] import the middleware plugin from nextauth 
- [ ] insert a new file in my route with the name middleware.js 
- [ ] compare your groups in your userdata with the data you want to reach, if you in the group, it returns the data, if not, getting an error with "unauthorized!".
- [ ] import middlewarefunctionality (the comparison) on each backend-request.
- [ ] ask thomas to attack again

## Size
Medium

**Comment by KevinKyaterekera** [comment]
Go for it! :D
