### ISSUE TITLE
user story (4 Create a Navigationbar)

### ISSUE THREAD

**Issue by jonas8900** [jonas8900/Capstone-project#6]
## Value proposition

As a user 
I want to have a navigation bar with a menu.
So i can switch the pages by clicking the icons.

## Description

![image](https://github.com/jonas8900/Capstone-project/assets/123127839/7a8e1ef7-04a7-42b1-9382-e5c2e46c8f07)

## Acceptance criteria

- at the bottom of the page are two icons, a home icon and a menu icon
- by clicking the home icon you will get to the Dashboard ( home ).
- by clicking the menu icon, a new page will appear with a selection, for now there's only the card "Aktivitäten"
- by clicking the card “Aktivitäten” you’ll get to the activities page. 

## Tasks

- [ ] create a new branch with the name “add-navigation-bar”
- [ ] create a new component with the name “NavigationBar”
- [ ] create a ul for the icons with the name NavbarWrapper
- [ ] in the ul paste two svg icons as list items, one home icon and one menu icon
- [ ] wrap a link with the route as href around the list items. 
- [ ] create a new page in pages with the name “menu”
- [ ] create a card with the route to the activity-list like the one in the preview.
- [ ] import the NavigationBar component on each page (menu, activities, index).
- [ ] in the menu page import a X icon and put it on the top and right corner. 
- [ ] the X is a route to the Dashboard so the User get the feeling to close a shortcut

## Size
small

**Comment by jonas8900** [comment]
i've decided to not implement the last two points, i'll do that later, if i think i'ts important.
