### ISSUE TITLE
User story 5 (Add delete possibility for each activity)

### ISSUE THREAD

**Issue by jonas8900** [jonas8900/Capstone-project#9]
## Value proposition Add delete possibility for each activity

as a user 
i want to have a possibility to delete the activity
to be able to remove wrong or boring activitys

## Description

![image](https://github.com/jonas8900/Capstone-project/assets/123127839/cfcb33f7-7716-4c15-98dd-6f547c72f65a)

## Acceptance criteria

- each list item in the activitylist has a “x” on the top in the left corner.
- by clicking the “x” a request appears with the Text “Do you really want to delete the activity?” with 2 response possibilities: “yes” or “cancel”.
- by clicking “ok” the card will be deleted, by clicking “cancel” the card stays.
- each item in the activitylist has a “plan” button (this doesn’t need a seperate userstory)

## Tasks

- [ ] create a branch with the name “add delete button”
- [ ] go to the Activitylist component and add a button with a “+” and a “planen” in the map function that each card have both buttons.
- [ ] add a handleDelete function which will display the cards without the deleted one.
- [ ] add a async function which dislays a request window with an ok and a cancel button.

## Size
small

**Comment by izabelladobielewska** [comment]
Hi Jonas, this looks ready to go :)
